### ISSUE TITLE
Error when running code!

### ISSUE THREAD

**Issue by usalexsantos** [Lucia-Ningning/Adaptive_Fusion_RGBD_Saliency_Detection#1]
I was trying to run your code to test the results but I'm getting an error.

D:\Adaptive_Fusion>python run_saliency.py
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
ImportError: numpy.core.multiarray failed to import

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 980, in _find_and_load
SystemError: <class '_frozen_importlib._ModuleLockManager'> returned a result with an error set
ImportError: numpy.core._multiarray_umath failed to import
ImportError: numpy.core.umath failed to import
2019-02-18 16:17:54.300853: F tensorflow/python/lib/core/bfloat16.cc:675] Check failed: PyBfloat16_Type.tp_base != nullptr

Am I doing something wrong?

**Comment by Lucia-Ningning** [comment]
Maybe you could try `pip install -U numpy`.

**Comment by usalexsantos** [comment]
Thank you Lucia-Ningning, I had to reinstall and now I'm getting another error.

D:\Adaptive_Fusion>python run_saliency.py
Traceback (most recent call last):
  File "run_saliency.py", line 6, in <module>
    from net import *
  File "D:\Adaptive_Fusion\net.py", line 2, in <module>
    import tensorflow.contrib.slim as slim
ModuleNotFoundError: No module named 'tensorflow.contrib.slim'

Maybe something wrong with my environment.
